version: 0

phases:
  build:
    commands:
      - aws deploy push --application-name AppforWork --s3-location s3://lastwork-bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
